name: Deploy changed services to prod

on:
  push:
    branches:
      - main
    paths:
      - 'backend_rds/**'
      - 'backend_redis/**'
      - 'frontend/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ecr-login-status: ${{ steps.ecr-login.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 638693734667.dkr.ecr.us-east-1.amazonaws.com

      - name: Install Make
        run: sudo apt-get install make

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Filter changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend_rds:
              - 'backend_rds/**'
            backend_redis:
              - 'backend_redis/**'
            frontend:
              - 'frontend/**'

  build-and-push-backend-rds:
    needs: setup
    if: ${{ github.event.head_commit.modified && contains(github.event.head_commit.modified, 'backend_rds/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push backend_rds
        run: |
          make image TARGET_FOLDER=backend_rds
          make push TARGET_FOLDER=backend_rds
          make update-compose TARGET_FOLDER=backend_rds
          cat build/docker-compose.yml


  build-and-push-backend-redis:
    needs: setup
    if: ${{ needs.setup.outputs.backend_redis == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push backend_redis
        run: |
          make image TARGET_FOLDER=backend_redis
          make push TARGET_FOLDER=backend_redis
          make update-compose TARGET_FOLDER=backend_redis

          cat build/docker-compose.yml

  build-and-push-frontend:
    needs: setup
    if: ${{ github.event.head_commit.modified && contains(github.event.head_commit.modified, 'frontend/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push frontend
        run: |
          make image TARGET_FOLDER=frontend
          make push TARGET_FOLDER=frontend
          make update-compose TARGET_FOLDER=frontend
          cat build/docker-compose.yml

  deploy-to-ec2:
    needs:
      - build-and-push-backend-rds
      - build-and-push-backend-redis
      - build-and-push-frontend
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-push-backend-rds.result == 'success' || needs.build-and-push-backend-redis.result == 'success' || needs.build-and-push-frontend.result == 'success' }}

    steps:
      - name: Connect to EC2 and deploy with docker-compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./
          target: /home/ubuntu/workdir/
          script: |

            make up
#            cd /home/ubuntu/workdir/

#            make down
#            make clean